#!/bin/bash

# Author: John Smith
# Date Created: 03/09/2022
# Date Modified: 03/09/2022

# Description: Backs up 'Documents' folder.

# Usage: ./backup_script

current_dir="$(pwd)"
echo "Hello, ${USER^}"
echo "I will now back up your 'Documents' directory, ${HOME}/Documents"
echo "Your are running this script form ${current_dir}" 
echo "Therefore, I will save the backup in ${current_dir}"

tar -cf ${current_dir}/my_backup_$(date +%d-%m-%Y_%H-%M-%S) ~/Documents 2> /dev/null
echo "Backup done successfully!"
exit 0

