#!/bin/bash

if [ $# -lt 3 ] 
then
    printf "%b" "ERROR. Not enough arguments.\n" >&2
    printf "%b" "Usage: myscript file op file1.\n" >&2
    exit 1
elif (( $# > 3 ))
then
    printf "%s" "Error. Too many arguments.\n" >&2
    printf "%s" "Usage: myscript file op file1.\n" >&2
else
    printf "%s" "Argument count correct. Proceding...\n"
fi


